# Script for creating the main repository of ibm wmq

#Creating QMGR Repository 1
crtmqm -u SYSTEM.TMXREPO01.DEAD.LETTER.QUEUE TMXREPO01

strmqm TMXREPO01
runmqsc TMXREPO01

ALTER QMGR REPOS(TMXCLUS01)

DEFINE CHANNEL(TO.TMXREPO01.TMX01) +
	CHLTYPE(CLUSRCVR) +
	TRPTYPE(TCP) +
	CONNAME('conname(15010)') +
	CLUSTER(TMXCLUS01) +
	DESCR('CLUSRCVR TMXREPO01')
	
DEFINE CHANNEL(TO.TMXREPO02.TMX01) +
	CHLTYPE(CLUSSDR) +
	TRPTYPE(TCP) +
	CONNAME('conname(15020)') +
	CLUSTER(CLUSTERNAME) +
	DESCR('CLUSSDR TMXREPO02')

end





#Removing the QM from the cluster

strmqm XXXX
ALTER CHANNEL(TO.XXXX.TMX01) CLUSTER('')
ALTER CHANNEL(TO.TMXREPO01.TMX01) CLUSTER('')

end
