#!/bin/sh
#Script for creating the main repository of ibm wmq
#Creating QMGR Repository 1


echo crtmqm -u SYSTEM.TMXREPO01.DEAD.LETTER.QUEUE TMXREPO01
echo strmqm TMXREPO01

echo ALTER QMGR REPOS(TMXCLUS01)

echo DEFINE CHANNEL(TO.TMXREPO01.TMX01) \
	CHLTYPE(CLUSRCVR) \
	TRPTYPE(TCP) \
	CONNAME('conname(15010)') \
	CLUSTER(TMXCLUS01) \
	DESCR('CLUSRCVR TMXREPO01') >%REPOS1%.in
	
echo DEFINE CHANNEL(TO.TMXREPO02.TMX01) \
	CHLTYPE(CLUSSDR) \
	TRPTYPE(TCP) \
	CONNAME('conname(15020)') \
	CLUSTER(CLUSTERNAME) \
	DESCR('CLUSSDR TMXREPO02') >%REPOS1%.in

runmqsc TMXREPO01 <%REPOS1%.in >%REPOS1%.out

type %REPOS1%.out

pause
