#Removing TMXREPO01 from cluster 
echo " ALTER CHANNEL(TO.TMXREPO01.TMX01) CHLTYPE(CLUSRCVR) CLUSTER('')" | runmqsc TMXREPO01
echo " ALTER CHANNEL(TO.TMXREPO02.TMX01) CHLTYPE(CLUSSDR) CLUSTER('')" | runmqsc TMXREPO01

