#Creating QMGR Repository 2
crtmqm -u SYSTEM.TMXREPO02.DEAD.LETTER.QUEUE TMXREPO02

strmqm TMXREPO02
runmqsc TMXREPO02

ALTER QMGR REPOS(TMXCLUS01)

DEFINE CHANNEL(TO.TMXREPO02.TMX01) +
	CHLTYPE(CLUSRCVR) +
	TRPTYPE(TCP) +
	CONNAME('conname(15020)') +
	CLUSTER(TMXCLUS01) +
	DESCR('CLUSRCVR TMXREPO02')
	
DEFINE CHANNEL(TO.TMXREPO01.TMX01) +
	CHLTYPE(CLUSSDR) +
	TRPTYPE(TCP) +
	CONNAME('conname(15010)') +
	CLUSTER(CLUSTERNAME) +
	DESCR('CLUSSDR TMXREPO01')

end
