#Creating QMGR Repository 2
crtmqm -u SYSTEM.TMXREPO02.DEAD.LETTER.QUEUE TMXREPO02

strmqm TMXREPO2

echo "ALTER QMGR REPOS(TMXCLUS01)" >>REPO2.in

echo "DEFINE CHANNEL(TO.TMXREPO02.TMX01)" \
	"CHLTYPE(CLUSRCVR)" \
	"TRPTYPE(TCP)" \
	"CONNAME('fintecheando-wmq-repo-02.bitnamiapp.com(15020)')" \
	"CLUSTER(TMXCLUS01)" \
	"DESCR('CLUSRCVR TMXREPO02')" >>REPO2.in
	
echo "DEFINE CHANNEL(TO.TMXREPO01.TMX01)" \
	"CHLTYPE(CLUSSDR)" \
	"TRPTYPE(TCP)" \
	"CONNAME('fintecheando-wmq-repo-01.bitnamiapp.com(15010)')" \
	"CLUSTER(CLUSTERNAME)" \
	"DESCR('CLUSSDR TMXREPO01')" >>REPO2.in

runmqsc TMXREPO02 <REPO2.in >REPO2.out
