#Creating QM in the cluster

crtmqm -u SYSTEM.XXXX.DEAD.LETTER.QUEUE XXXX
strmqm XXXX
runmqsc XXXX

DEFINE CHANNEL(TO.XXXX.TMX01) +
	CHLTYPE(CLUSRCVR) +
	TRPTYPE(TCP) +
	CONNAME('CONNAME()') + 
	CLUSTER(TMX01)

DEFINE CHANNEL(TO.TMXREPO01.TMX01) + 
	CHLTYPE(CLUSSDR) + 
	TRPTYPE(TCP) + 
	CONNAME('CONNAME(16000)') +
	CLUSTER(TMX01)
	
end
